baseurl = "/"
theme = "hugo-casper-two"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
languageCode = "pl"
languageName = "Polski"
defaultContentLanguage = "pl"
title = "siepodrozuje.pl - Blog podróżniczy"

[params]
#  title = "Blog"
#  subtitle = "blog"

  cover = "/img/bergen09.jpg"
  description = "Blog podróżniczy"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = ""

  logo = "/img/logo.png"
#  orgName = ""
#  orgWebsite = ""
#  orgDescription = ""

  author = "Martyna & Marcin"
  authorAvatar = "/img/avatar.jpg"
#  authorLocation = ""
#  authorWebsite = ""
  authorDescription = "Podróżujemy i wgl"

  pageNotFoundTitle = "404 - nic tu nie ma :("

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/posts/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Travel"
  url = "/categories/travel/"
  weight = 99
